#modified
name: Go
on: [push]
jobs:
#
  job_1:
    name: job_1 demonstrates the print of a String
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "Hello" > math-homework.txt
      - name: Upload stdout result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
 
  job_2:
    name: job_2 demonstrates the priint of another String value
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download data from job_1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo $value \+ "World!" > homework/math-homework.txt
      - name: Upload string result for Job2
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: homework/math-homework.txt
  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework

on: push